Repository kryoniteorg/kryo-server-discovery, pull requests merged in 2022-01, with the labels that each got.

#7 Fix dependency version extraction for dependabot
  build.gradle.kts
Labels: bug

#10 feat: Add Sonarcloud badges to README.md
  README.md
Labels: enhancement

#12 feat: Add release-drafter and label sync
  .github/release-drafter.yml
  .github/workflows/label-sync.yaml
  .github/workflows/release-drafter.yaml
Labels: enhancement

#13 fix: Rename to KryoniteOrg to fit domain
  .github/workflows/label-sync.yaml
  .github/workflows/main.yaml
  .github/workflows/release-drafter.yaml
  .github/workflows/wrapper-validation.yaml
  README.md
  build.gradle.kts
Labels: bugfix
